version: '2'
services:


  logspout:
      image: muccg/logspout-logstash
      environment:
        - WAIT_FOR_LOGSTASH=1
        - RETRY_STARTUP=1
        - ROUTE_URIS=logstash+tcp://logstash:5140
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      links:
        - logstash
      depends_on:
        - logstash

  kibana:
      image: docker.elastic.co/kibana/kibana:5.5.2
      volumes:
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      ports:
        - "5601:5601"
      links:
        - elasticsearch
      depends_on:
        - elasticsearch

  elasticsearch:
      # note: sudo chmod o+w data/elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
      environment:
        - http.host=0.0.0.0
        - transport.host=127.0.0.1
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      mem_limit: 1g
      volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data
      ports:
        - "9200"
        - "9300"

  logstash:
      image: docker.elastic.co/logstash/logstash:5.5.2
      environment:
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      mem_limit: 1g
      volumes:
        - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
        - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      links:
        - elasticsearch
      ports:
        - "5140:5140"
        - "5140:5140/udp"
        - "514"
        - "514/udp"
        - "5959"
        - "5959/udp"
      depends_on:
        - elasticsearch 

  # throw away nginx container for local testing
  nginx:
      build: nginx/
      command: nginx
      environment:
        - WAIT_FOR_KIBANA=1
      ports:
        - "443"
      links:
        - kibana
      depends_on:
        - kibana
